production:
  sessions:
    default:
      database: idea_box_production
      uri:
        - <%= ENV['MONGODB_URI'] %>

development:
  sessions:
    default:
      database: idea_box_development
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: idea_box_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
