production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>

development:
  clients:
    default:
      database: idea_box_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: idea_box_test
      hosts:
        - localhost:27017
